service=whostmgr
url=/cgi/imh-backup-manager/index.php
user=root
phpHandler=/php/83/etc
features=any
displayname=Backup Manager
acls=any
entryurl=imh-backup-manager/index.php
target=_self
icon=imh-backup-manager.png
name=imh-backup-manager
description=InMotion Hosting Backup Manager - Configure, Monitor, and Restore Backups
